# Generated by Django 5.2.4 on 2025-07-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('catalog', models.CharField(choices=[('tech', 'Технология'), ('сlothing', 'Одежда'), ('furniture', 'Мебель'), ('automotive', 'Автотовар'), ('tourism', 'Туризм'), ('drugstore', 'Аптека')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
