# Generated by Django 5.2.4 on 2025-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
