# Generated by Django 5.2.4 on 2025-08-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyofsystem',
            old_name='type',
            new_name='type_of',
        ),
    ]
